### ISSUE TITLE
Python 2-related code in the rest_api.py

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-data-model#196]
Do we plan to remove all the Python 2-related code from this repository?

```
api_v1 = Blueprint('api_v1', __name__)

# Python2.x: Make default encoding as UTF-8
if sys.version_info.major == 2:
    reload(sys)
    sys.setdefaultencoding('UTF8')
```

IMHO it is not much relevant these days...

**Comment by yzainee** [comment]
@tisnik Yes we plan to change everything from python2 to python3. I missed this change. I am waiting for a merge to happen on the base image https://github.com/rhdt/EL-Dockerfiles/pull/77. After that i will commit the rest_api.py changes

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/239
