### ISSUE TITLE
Remove gremlin-python imports from graph manager and requirements.txt

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-data-model#49]
As we are no longer dependent on the `gremlin-python-websocket`, we can safely remove it from the following files:
Starting `line4` to `line8` in `graph_manager` [here](https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/src/graph_manager.py#L4)
And `line7` in `requirements.txt` [here](https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/requirements.txt#L7)

**Comment by tuxdna** [comment]
Imports were removed in this commit: https://github.com/fabric8-analytics/fabric8-analytics-data-model/commit/1df591aedcc68277c3f1de7ebcfbda9eed270c44#diff-6c3b9ca7fe65fa3897283181b11c7881L6
